version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - metanet
    restart: unless-stopped
  
volumes:
  mysql_data:

networks:
  metanet:
    name: metanet
    driver: bridge
    external: true